### PR TITLE
feat: remove python 2.7 references, add build,

### PR DESCRIPTION
**Pull request by techsolx**
* opencv2 and ros are fully python 3 capable now
    * /online-labs repo is updated to python 3, thank you @bobcassels
    * ran make clean, removing the _build dir
    * updated the piazza links
    * cleaned up conf.py
    * added requirements.txt file for build
    * add .github/workflow
    * make clean local copy
    * push to github, check gh-pages, on automated build
    * this looks like more changes that it really is due to `make clean`

View changes here: https://techsolx.github.io/website-MITLL-BWSI-MS/

ToDo: Add github token,

    * owner of main repo @sabinach or @sertackaraman or @bobcassels
    * add Personal Access Token under developer settings, copy token
    * Then add it as secret named TOKEN_MITLL_RACECAR in target repo
    * merge to master and gh-pages will build
    * Someone with an @mit.edu address needs to update piazza
    * update google/docs Anaconda Python 2.7 no longer available https://docs.google.com/document/d/1IBV25Wrk2XgS7Xtwo6VbOBgRdlEv5sZyZWhrb94gW1I/edit
    * fix broken links to Jupyter nbviewer in Module 1:Python from Data Types on down, I don't have access to those in the GDrive
    *  add .gitignore so all the _build stuff is not show

If or when you change the default branch from master to main, you many need to update the `.github/workflows/build-sphinx.yaml`

Change:
```
on:
  push:
    branches:
      - '**'
```
To:
```
on:
  push:
    branches:
      - main
```

That way the build to gh-pages will only happen on the default branch.

MIT-CW-012011 6.5h

### CODE REVIEW

**Comment by techsolx** [comment]
By way of introduction, I am John and I am working as a TA for the BWSI-Kwajalein program.

**Comment by techsolx** [comment]
@sabinach I have updated and checked the .rst changes you suggested.  They are tested and working on my main branch, you can see them here:
https://techsolx.github.io/website-MITLL-BWSI-MS/docs/curriculum/opencv/drawing.html

Thank you!

**Comment by sabinach** [comment]
@techsolx Great, please add yourself as a contributor here, and let me know when this PR is ready to merge to the main website branch:
https://github.com/mit-bwsi-racecar-ms/website/blob/master/docs/resources/contributors.rst#contributors-1

**Comment by techsolx** [comment]
@sabinach Changes above are complete.  PR is ready to merge.  Thank you, BWSI is a wonderful program.

**Review by sabinach — APPROVED** [review]

**Pull request merged**
